apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./flux-system/
- ./aws-load-balancer-controller/
- ./gitlab/
- ./logging/
- ./cluster-autoscaler/
- ./aws-node-termination-handler/
- ./secrets-store-csi/
